# Generated by Django 5.2.17 on 2026-09-29 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('EntrepriseApp', '0002_rename_created_at_utilisateur_created_at_entreprise_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expedition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=50, unique=True)),
                ('ville_depart', models.CharField(max_length=80)),
                ('ville_arrive', models.CharField(max_length=80)),
                ('poids_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_souhaitee', models.DateTimeField()),
                ('description', models.TextField()),
                ('statut', models.CharField(choices=[('en_attente', 'en_attente'), ('t', 'terminee'), ('a', 'annulee')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entreprise', to='EntrepriseApp.entreprise')),
            ],
        ),
    ]
