# Generated by Django 5.2.17 on 2026-10-06 15:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExpeditionApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expedition',
            name='poids_kg',
            field=models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(0.001, 'Le poids doit être supérieur à 0 kg')]),
        ),
    ]
