# Generated by Django 5.2.17 on 2026-09-29 19:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EntrepriseApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='utilisateur',
            old_name='Created_at',
            new_name='created_at',
        ),
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raison_social', models.CharField(max_length=200)),
                ('matricule_fiscale', models.CharField(max_length=17, unique=True)),
                ('adresse', models.TextField()),
                ('type_entreprise', models.CharField(choices=[('c', 'Chargeur'), ('t', 'Transporteur')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gerant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Entreprise', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='EntrepriseApp',
        ),
    ]
