# Generated by Django 5.2.17 on 2026-10-06 13:47

import EntrepriseApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EntrepriseApp', '0003_alter_entreprise_adresse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[EntrepriseApp.models.validate_email]),
        ),
    ]
