# Generated by Django 5.2.17 on 2026-10-06 14:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EntrepriseApp', '0004_alter_utilisateur_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entreprise',
            name='matricule_fiscale',
            field=models.CharField(max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message='Format erroné', regex='^\\d{7}[/ -]?[A-Za-z][/ -]?[ABDNPEabdnpe][/ -]?[MPCNEmpcne][/ -]?\\d{3}$')]),
        ),
    ]
