# Generated by Django 5.2.17 on 2026-10-06 15:25

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EntrepriseApp', '0005_alter_entreprise_matricule_fiscale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entreprise',
            name='adresse',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(20, "L'adresse ne peut pas avoir moins de 20 caractères."), django.core.validators.MaxLengthValidator(400, "L'adresse ne peut pas dépasser 400 caractères.")]),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='gerant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='entreprise', to=settings.AUTH_USER_MODEL),
        ),
    ]
