# Generated by Django 5.2.17 on 2026-09-29 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('EntrepriseApp', '0002_rename_created_at_utilisateur_created_at_entreprise_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('immatriculation', models.CharField(max_length=50, unique=True)),
                ('type_vehicule', models.CharField(choices=[('c', 'camionnette'), ('f', 'fourgon'), ('sr', 'semi-remorque'), ('cp', 'camion porteur')], max_length=100)),
                ('capacite_kg', models.PositiveIntegerField()),
                ('disponible', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicules', to='EntrepriseApp.entreprise')),
            ],
        ),
    ]
