# Generated by Django 5.2.17 on 2026-10-06 13:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VehiculeApp', '0002_remove_vehicule_disponible_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicule',
            name='entreprise',
        ),
        migrations.AddField(
            model_name='vehicule',
            name='disponible',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='capacite_kg',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(100, 'La capacité doit être superieur de  0 kg')]),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='immatriculation',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='type_vehicule',
            field=models.CharField(choices=[('f', 'electrique'), ('t', 'hybride')], default='f'),
        ),
    ]
